# Automatically generated by updatesources.sh
# on  Wed Jan 20 11:54:28 EST 2016

HEADERS += \
     cms/CMSProfile.h  \
     cms/CMSTransform.h  \
     cms/CMS.h  \

SOURCES += \
     cms/CMSProfile.cpp  \
     cms/CMSTransform.cpp  \

RESOURCES += \

FORMS += \

