# Automatically generated by updatesources.sh

HEADERS += \
     cms/CMSProfile.h  \
     cms/CMS.h  \
     cms/ThreadedTransform.h  \
     cms/CMSTransform.h  \

SOURCES += \
     cms/CMSTransform.cpp  \
     cms/ThreadedTransform.cpp  \
     cms/CMSProfile.cpp  \

RESOURCES += \

FORMS += \

