######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 20 20:25:48 2015
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11	

# Input
HEADERS += Image.h ImageConverters.h
SOURCES += Image.cpp ImageConverters.cpp 
