#!/usr/bin/perl -w

use strict;

# The table we construct will have entries 0xTTTWWWIIII where
#   TTT represents the tele end of the lens's focus range in mm,
#   WWW represents the wide end of the lens's focus range in mm,
#   IIII represents the LensType.
# This is done because multiple lenses exist for a given LensType.

open IN, "canonlenses.txt" or die "Cannot read canonlenses.txt\n";
open OUT, ">efmountlens.h" or die "Cannot read efmountlens.h\n";

print OUT "// efmountlens.h - database of Canon lenses\n";
print OUT "// Automatically generated by canonlenses2c.pl\n";
print OUT "\n";

while (<IN>) {
  chomp;
  s/\#.*//;
  s/^\s+//;
  s/\s+$//;
  next if /^$/;
  /^(\d+)(\.\d+)?\s+=\s+(.*)/ or next;
  my $id = $1;
  my $name = $3;
  unless ($name =~ /(\d+)(-(\d+))?mm/) {
    warn "No focal length info in '$name' ($id) - skipping\n";
    next;
  }
  my $f_low = $1;
  my $f_high = (defined $3) ? $3 : $f_low;
  $name =~ s/\s+or\s+.*//;
  $id = sprintf("0x%010x", 65536*$f_low + 65536*4096*$f_high + $id);
  print OUT "lenses.insert($id, \"$name\");\n";
}
