#!/bin/bash

SUBDIRS="corelib cms db adj ui dlg"
APP=photohoard

cd `dirname $0`
cd ../src

echo "# Automatically generated by updatesources.sh" > $APP.pri
echo "" >> $APP.pri
echo "sourcedirs = \\" >> $APP.pri

for DIR in $SUBDIRS; do
    echo "    $DIR \\" >> $APP.pri

    echo "# Automatically generated by updatesources.sh" > $DIR/$DIR.pri
    echo "" >> $DIR/$DIR.pri
    echo "HEADERS += \\" >> $DIR/$DIR.pri
    find $DIR -name \*.h -exec echo "    " '{}' " \\" ';' >> $DIR/$DIR.pri
    echo "" >> $DIR/$DIR.pri

    echo "SOURCES += \\" >> $DIR/$DIR.pri
    find $DIR -name \*.cpp -exec echo "    " '{}' " \\" ';' >> $DIR/$DIR.pri
    echo "" >> $DIR/$DIR.pri

    echo "RESOURCES += \\" >> $DIR/$DIR.pri
    find $DIR -name \*.qrc -exec echo "    " '{}' " \\" ';' >> $DIR/$DIR.pri
    echo "" >> $DIR/$DIR.pri

    echo "FORMS += \\" >> $DIR/$DIR.pri
    find $DIR -name \*.ui -exec echo "    " '{}' " \\" ';' >> $DIR/$DIR.pri
    echo "" >> $DIR/$DIR.pri
done

echo "" >> $APP.pri
