#!/bin/sh

SUBDIRS="corelib cms db adj ui dlg"
APP=photohoard

cd `dirname $0`
PFX=../src/

echo "# Automatically generated by updatesources.sh" > $APP.pri
echo "" >> $APP.pri
echo "sourcedirs = \\" >> $APP.pri

for DIR in $SUBDIRS; do
    echo "    $PFX$DIR \\" >> $APP.pri

    echo "# Automatically generated by updatesources.sh" > $PFX$DIR/$DIR.pri
    echo "" >> $PFX$DIR/$DIR.pri
    echo "HEADERS += \\" >> $PFX$DIR/$DIR.pri
    find $PFX$DIR -name \*.h -exec echo "    " '{}' " \\" ';' >> $PFX$DIR/$DIR.pri
    echo "" >> $PFX$DIR/$DIR.pri

    echo "SOURCES += \\" >> $PFX$DIR/$DIR.pri
    find $PFX$DIR -name \*.cpp -exec echo "    " '{}' " \\" ';' >> $PFX$DIR/$DIR.pri
    echo "" >> $PFX$DIR/$DIR.pri

    echo "RESOURCES += \\" >> $PFX$DIR/$DIR.pri
    find $PFX$DIR -name \*.qrc -exec echo "    " '{}' " \\" ';' >> $PFX$DIR/$DIR.pri
    echo "" >> $PFX$DIR/$DIR.pri

    echo "FORMS += \\" >> $PFX$DIR/$DIR.pri
    find $PFX$DIR -name \*.ui -exec echo "    " '{}' " \\" ';' >> $PFX$DIR/$DIR.pri
    echo "" >> $PFX$DIR/$DIR.pri
done

echo "" >> $APP.pri
